name: openemr
description: A new Flutter project.

version: 3.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auth_buttons: ^3.0.2
  barcode_widget: ^2.0.4
  camera: ^0.10.5+4
  charts_flutter_new: ^0.12.0
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.6
  dash_chat: ^1.1.8
  email_validator: ^2.1.17
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_ml_vision: ^0.12.0+3
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_progress_hud: ^2.0.2
  flutter_webrtc: ^0.9.41
  getwidget: ^4.0.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_picker: ^1.0.4
  json_store: ^2.0.1
  lints: ^2.1.1
  shared_preferences: ^2.2.1
  wakelock: ^0.6.2
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/image.png
    - lib/assets/images/image1.png
    - lib/assets/images/red.png
    - lib/assets/images/purple.png
    - lib/assets/images/pink.png
    - lib/assets/images/orange.png
    - lib/assets/images/image2.png
    - lib/assets/images/img.png
    - lib/assets/images/img1.png
    - lib/assets/images/img2.png
    - lib/assets/images/card.png
    - lib/assets/images/card1.png
    - lib/assets/images/card2.png
    - lib/assets/images/card3.png
    - lib/assets/images/card5.png
    - lib/assets/images/card4.png
    - lib/assets/images/gflogo.png
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/avatar5.png
    - lib/assets/images/avatar6.png
    - lib/assets/images/avatar7.png
    - lib/assets/images/avatar8.png
    - lib/assets/images/avatar9.png
    - lib/assets/images/avatar10.png
    - lib/assets/images/avatar11.png
    - lib/assets/images/avatar12.png
    - lib/assets/images/firebase.png
    - lib/assets/gif/success1.gif
    - lib/assets/icons/gflogo.png
    - lib/assets/images/logo.png

  fonts:
    - family: GFFontIcons
      fonts:
        - asset: lib/assets/fonts/gfFontIcon.ttf
          weight: 400

    - family: GFFontIcons2
      fonts:
        - asset: lib/assets/fonts/gfFontIcons2.ttf
          weight: 400

    - family: GFSocialFonts
      fonts:
        - asset: lib/assets/fonts/gfSocialFonts.ttf
          weight: 400

    - family: GFIconFonts
      fonts:
        - asset: lib/assets/fonts/gfIconFonts.ttf
          weight: 400

    - family: GFIcons
      fonts:
        - asset: lib/assets/fonts/loader.ttf
          weight: 400
